### ISSUE TITLE
[Feature Request] FileSync Protocol

### ISSUE THREAD

**Issue by matthieuxyz** [JeffLIrion/adb_shell#41]
Hello,

Python-abd, implements the FileSync protocol in addition to the shell. (Push in particullar) Is it planned to include FileSync in the adb_shell project?

Also, the python-abd, has a hard-coded limit of 2ko per message, do you know why? Is it possible to increase this limit?

**Comment by JeffLIrion** [comment]
> Python-abd, implements the FileSync protocol in addition to the shell. (Push in particullar) Is it planned to include FileSync in the adb_shell project?

I don't plan to add that functionality because I don't use it, but anyone is welcome to contribute it. As long as it has full test coverage and it's well documented, I'll review and accept the pull request. 

> Also, the python-abd, has a hard-coded limit of 2ko per message, do you know why? Is it possible to increase this limit?

For reference: https://github.com/google/python-adb/blob/f4e597fe55900651a8a91fccc1e09061fd96b5e9/adb/filesync_protocol.py#L146-L154

I don't know because I haven't used the filesync protocol. But I think it will continue to read `datafile` in 2048 byte size chunks until the whole file has been sent.

**Comment by JeffLIrion** [comment]
With the current foundation in place, it seemed like it wouldn't be too difficult to implement the FileSync protocol, so I started working on it. Here's the branch: https://github.com/JeffLIrion/adb_shell/tree/filesync

It's definitely not done -- there are some errors in the code. And I won't merge it in until it has unit test coverage. But it's a start.

**Comment by JeffLIrion** [comment]
Implemented in https://github.com/JeffLIrion/adb_shell/pull/42.  I bumped the version to 0.0.9 and published a new release on pypi.
