### ISSUE TITLE
USB support?

### ISSUE THREAD

**Issue by Halastra** [JeffLIrion/adb_shell#50]
Is there currently any way to connect to a device over USB?
It seems like this is not implemented yet, but I thought I'd ask.. just in case I'm missing something.

**Comment by JeffLIrion** [comment]
Currently, no. But if someone would like to contribute that functionality, it would be welcome! It was discussed a bit in this issue: https://github.com/JeffLIrion/adb_shell/issues/37. 

> I wrote this package to implement ADB shell functionality over TCP. If someone wants to implement that same functionality over USB, including writing tests with complete coverage, then that would be a welcome contribution. But I have no plans to do that myself.

**Comment by Halastra** [comment]
Challenge accepted.

**Comment by JeffLIrion** [comment]
I did some initial work on this, porting over the USB handle from the python-adb repo. There are no tests for it (I did copy over the `TcpHandle` tests, which can be used as a guide, but I made it so that all they currently do is return immediately). I don't know if the code works. But if you're still interested in implementing this, it's a good starting point. 

https://github.com/JeffLIrion/adb_shell/tree/usb-support

**Comment by Halastra** [comment]
Wow, that's great to see!
I've actually started working on an implementation (also porting from `python-adb`), but I ran into some issues.
I'll try and see if your code works. If it does, it will save me a lot of work.
As soon as I get a working version (yours or mine) I will certainly fork from this branch.

**Comment by JeffLIrion** [comment]
You should push your work to your fork, that way I can see what you've done so far. 

I want `UsbHandle` to have the same signatures as `TcpHandle` for the four main methods: `close`, `connect`, `bulk_read`, and `bulk_write`. Other than that, you can change pretty much whatever you want. 

I also want USB support to be an "extra" for this package, meaning that the user will need to do `pip install adb-shell[usb]`. I think that's what this accomplishes:

https://github.com/JeffLIrion/adb_shell/blob/f9e026b773a22f5d30e3b86e97942abeef2cacc3/setup.py#L18

That's because it requires certain libraries to be installed on the system (`libusb-1.0`, I believe), and I don't want `pip install adb-shell` to fail or throw warnings if the user doesn't have this.

**Comment by Halastra** [comment]
I just pushed a basic working commit to my fork.
- Implemented `AdbDeviceUsb`
- Added some missing pieces in `UsbHandle`

My fork _may_ be functional, but it is not PR-ready yet.
Documentation, tests and refactoring still needed before merging.

**Comment by Halastra** [comment]
Regarding my previous note on some issues, our ports were fairly similar, so I've done some additional testing. 
Turns out that the results depend on the device model:
- OnePlus 5T hangs
- Xiaomi Redmi Note 4 works

Notes regarding my tests:
- Ran manually on my machine (Windows 10). 
- Results are consistent between `adb-shell` and `python-adb`.

I haven't seen any related issues posted on `python-adb`, so I suspect this might have something to do with my setup.
I'd appreciate any advice regarding this matter.

**Comment by JeffLIrion** [comment]
Thanks for working on this! Given that you have achieved some level of functionality, you should submit a pull request to my `usb-support` branch. It’s a work-in-progress branch, so don’t worry about not having it all finished up.

**Comment by AlopexMM** [comment]
Hi Jeff, i fork adb-shell and i get it woking usb-support branch on my linux Mint.
I tested a connection with an alcatel pixie 3 tablet and it worked.
I would like to help with the progress of this project, tell me that I can move forward to help bring this tool to production

**Comment by JeffLIrion** [comment]
Help would definitely be appreciated! At this point, what's needed is to add tests. There are some tests in https://github.com/JeffLIrion/adb_shell/blob/usb-support/tests/test_usb_handle.py, but at this time all they do is return immediately, they don't actually test anything. The TCP handle tests might be a useful reference: https://github.com/JeffLIrion/adb_shell/blob/usb-support/tests/test_tcp_handle.py

@Halastra anything to add?

Thanks!

**Comment by Halastra** [comment]
That's great news!
Indeed, the tests are what's most important right now. 

Of course, if  @AlopexMM found any bugs during the process, that's also important to address.

**Comment by AlopexMM** [comment]
Ok, i will be checking the test. i let you now when i finish.

Cheers
