### ISSUE TITLE
Handle object should be abstracted

### ISSUE THREAD

**Issue by cyanogen** [JeffLIrion/adb_shell#52]
Currently there is no way to pass an initialized or custom handle object to an AdbDevice. With python-adb, this could be done by calling ConnectDevice with handle set. This is useful for support custom handle implementations (in my case, I need to talk to a websocket via Twisted).

Happy to provide a patch. At this point I'm just investigating whether this library solves issues I'm having with python-adb.

**Comment by JeffLIrion** [comment]
That would be a welcome contribution! I think that the signature for `AdbDevice.__init__` should be

```python
def __init__(self, serial=None, handle=None, banner=None, default_timeout_s=None):
```

And the logic for the handle should be:

```python
if handle:
    # use the provided handle
else:
    # use `TcpHandle`
```

And if USB support gets added, this could be changed to:

```python
if handle:
    # use the provided handle
elif serial:
    # use `TcpHandle`
else:
    # use `UsbHandle`
```

**Comment by Halastra** [comment]
I'm currently working on a PR for USB support (#50), and I ran into the same issue.
If we really want to be abstract, I would suggest that the signature for `AdbDevice.__init__` be:
```
def __init__(self, handle, banner=None, default_timeout_s=None):
```
where `handle` is required to implement the specified interface (as `TcpHandle` currently does).

Additional class methods should be provided for convenience, such as:
```
@classmethod
    def from_tcp(cls, host, port=5555, **kwargs):
        tcp_handle = TcpHandle(host, port, **kwargs)
        return cls(tcp_handle, **kwargs)

@classmethod
    def from_usb(cls, device_serial, **kwargs):
        usb_handle = UsbHandle(host, port, **kwargs)
        return cls(usb_handle, **kwargs)
```

This change (or similar to it) will be part of my PR/s.

**Comment by JeffLIrion** [comment]
@cyanogen Here's a pull request that allows the user to provide a custom handle: https://github.com/JeffLIrion/adb_shell/pull/55.  Let me know what you think.  

@Halastra I don't want `handle` to be a required argument; I want it to be possible to instantiate the `AdbDevice` instance without first having to instantiate a handle and without having to use a classmethod.  If the user provides a handle, we'll use it.  Otherwise, we'll figure out whether to use a `TcpHandle` or `UsbHandle`* instance based on the provided arguments.  And I want to stay away from `*args` and `**kwargs`, I'd rather be upfront about what parameters are expected.  

*Once `UsbHandle` is implemented.

**Comment by Halastra** [comment]
>  If the user provides a handle, we'll use it. Otherwise, we'll figure out whether to use a TcpHandle or UsbHandle* instance based on the provided arguments

You _don't_ want to do that in your `__init__` method. That sounds really unhealthy. [Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/).
It means that `__init__` will have to change with every new type of handle you want to support.

I also have some comments regarding #55. I'll post them over there.

**Comment by JeffLIrion** [comment]
Closed by https://github.com/JeffLIrion/adb_shell/pull/55 and https://github.com/JeffLIrion/adb_shell/pull/57.

**Comment by cyanogen** [comment]
Awesome, thanks so much!
